version: '3.8'

services:
  # redis:
  #   entrypoint: ["echo", "Service foo disabled"]

  api-gateway:
    build: 
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-gateway:/usr/src/app
      - ./shared-types:/usr/src/shared-types
    ports:
      - "8080:8080"
  
  llm-service:
    build: 
      dockerfile: Dockerfile.dev
    volumes:
      - ./llm-service:/src
