version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - api-gateway
  
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports: 
      - ${API_GATEWAY_PORT}
      - ${WS_PORT}
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PORT=${API_GATEWAY_PORT}
      - HOST=${API_GATEWAY_HOST}
      - WS_PORT=${WS_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge