version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./shared-types:/usr/src/shared-types